builds:
  - id: meteor
    main: .
    binary: meteor
    flags:
      - "--trimpath"
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .Binary}}-{{ .Os }}-{{ .Arch }}"
brews:
  - name: meteor
    homepage: https://github.com/stefanlogue/homebrew-tools
    repository:
      owner: stefanlogue
      name: homebrew-tools
scoops:
  - name: meteor
    depends: ["git"]
    repository:
      owner: stefanlogue
      name: scoops
release:
  prerelease: auto
  github:
    owner: stefanlogue
    name: meteor
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix|chore)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
announce:
  linkedin:
    enabled: false
