version: 2
builds:
  - id: meteor
    main: .
    binary: meteor
    flags:
      - "--trimpath"
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
archives:
  - formats: [zip]
    name_template: "{{ .Binary}}-{{ .Os }}-{{ .Arch }}"
homebrew_casks:
  - name: meteor
    homepage: https://github.com/stefanlogue/homebrew-tools
    repository:
      owner: stefanlogue
      name: homebrew-tools
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/meteor"]
          end
scoops:
  - name: meteor
    depends: ["git"]
    homepage: "https://github.com/stefanlogue/scoops"
    license: MIT
    repository:
      owner: stefanlogue
      name: scoops
release:
  prerelease: auto
  github:
    owner: stefanlogue
    name: meteor
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix|chore)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
announce:
  linkedin:
    enabled: false
  bluesky:
    enabled: true
    username: stefanlogue.dev
    message_template: "{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}\n\n#go #golang #devops"
