Output demo-without-boards.gif

Require echo

Set Shell "bash"
Set FontSize 24
Set Width 1400
Set Height 1000

Type@250ms "git add demo-without-boards.tape" Enter
Type@250ms "meteor" Sleep 500ms Enter
Sleep 3s
Enter
Sleep 3s
Type@250ms "/docs"
Enter
Sleep 3s
Left@500ms
Right@500ms
Enter
Type@250ms "readme"
Sleep 2s
Enter
Sleep 2s
Down@500ms
Up@500ms
Type@250ms "x"
Sleep 2s
Enter
Type@250ms "update readme"
Enter
Sleep 2s
Type@250ms "add gifs from vhs"
Sleep 2s
Enter
Sleep 2s
Enter

Sleep 3s
